In [1]:
import pandas as pd
import numpy as np
import os
import data_process
dataPath = r"./data/"
# __dataList = os.listdir(dataPath)  # data file names
dataList = ["all.csv"]

set = data_process.loadData(dataPath=dataPath,dataList=dataList)
set.info()
print(set.shape)
print(set.tail())
assert not np.any(set.isnull()), "df has null"

*****
Loaded all.csv from ./data/
*****
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2567 entries, 0 to 2566
Data columns (total 6 columns):
content     2567 non-null object
anger       2567 non-null int64
fear        2567 non-null int64
joy         2567 non-null int64
sadness     2567 non-null int64
surprise    2567 non-null int64
dtypes: int64(5), object(1)
memory usage: 120.4+ KB
(2567, 6)
                                                content  anger  fear  joy  \
2562                 Kwon was one of Cicada's handlers.      0     0    0
2563                  What the fuck is going on, Ellen?      1     0    0
2564  I was there when that asset went rogue in New ...      0     0    0
2565                           I saw the hunt up close.      0     1    0
2566  He was doing what the agency wasn't willing to...      0     1    0

      sadness  surprise
2562        0         0
2563        0         0
2564        0         0
2565        0         0
2566        0         0

In [2]:
num_ones =data_process.dataInfo(set)

0*'1' numbers: 1286
1*'1' numbers: 1187
2*'1' numbers: 92
3*'1' numbers: 2
4*'1' numbers: 0
5*'1' numbers: 0

In [3]:
set.tail()
set=data_process.adjustData(set,num_ones,output_dir=r"./adjusted_data")
set.tail()

,content,anger,fear,joy,sadness,surprise
1276,Are they still back there?,0,0,0,0,1
1277,"Thanks for coming, Mom.",0,0,1,0,0
1278,"No traces, no tracks, nothing.",1,0,0,1,0
1279,I was hoping the surprise would take the stink...,0,0,1,0,0
1280,There's always another choice.,0,0,0,1,0

In [0]:
print(set.head())
print(set.tail())
print(set.shape)
# print(set.loc[1578])
# print(set.index[1578])
# print(set.index[0])